version: '3'

services:
  graysales:
    image: graysales-backend
    volumes:
      - .: /usr/src/app #/Users/pc/graysales-backend
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - graysales-network
    depends_on:
      - mongo
    command:  "npm run dev"

    mongo:
      image: mongo
      ports:
        - "27001:27001"
      networks:
        - graysales-network
      volumes:
        - mongodb:/data/db
        - mongodb_config:/data/configdb

volumes:
  mongodb:
    driver: local
  mongodb_config:
    driver: local

networks:
  graysales-network:
    driver: bridge

# services:
#   src:
#     image: graysales-app
#     volumes:
#       - ./:/src
#     env_file:
#       - .env
#     ports:
#       - '8080:8080'
#     networks:
#         - graysales
#     depends_on:
#       - mongo
#     command: [ "npm" , "run dev"]

#   mongo:
#       image: mongo
#       ports:
#         - "27001:27001"
#       networks:
#         - graysales
#       volumes:
#         - mongodb:/data/db
#         - mongodb_config:/data/configdb

# volumes:
#   mongodb:
#     driver: local
#   mongodb_config:
#     driver: local

# networks:
#   graysales:
#     driver: bridge
