version: '3'

services:
  graysales:
    image: graysales-backend
    volumes:
      - ./:/graysales

    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - graysales-network
    depends_on:
      - graysales-mongo
    command:  "npm run dev"

  graysales-mongo:
    image: mongo:5.0
    container_name: graysales-mongo
    ports:
      - "27001:27001"
    networks:
      - graysales-network
    volumes:
      - graysales-mongo:/data/db
      - graysales-mongo_config:/data/configdb

volumes:
  graysales-mongo:
    driver: local
  graysales-mongo_config:
    driver: local

networks:
  graysales-network:
    driver: bridge

