# Use an official Node.js runtime as a parent image
FROM node:18-slim

# Set the working directory to /app
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Compile the TypeScript code to JavaScript
RUN npm run build

# Expose the port that the application will listen on
EXPOSE 8080

# Start the application
CMD ["npm", "run dev"]




# FROM node:18-slim as builder

# # Create app directory
# WORKDIR /usr/src

# # Install app dependencies
# COPY package*.json ./
# ARG NODE_ENV
# RUN if ["$NODE_ENV"="development"]; then npm install; else npm install --only=production; fi
# COPY . .

# # Build app
# FROM node:18-slim
# COPY --from=builder /usr/src /usr/src

# WORKDIR /usr/src/

